# Generated by Django 5.2 on 2026-02-21 13:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0008_phase1_hotel_tier_redesign"),
        ("pricing_engine", "0002_alter_pricingrule_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingrule",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="pricingrule",
            name="active_to",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Leave blank for indefinite validity",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pricingrule",
            name="is_percentage",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="True for percentage, False for fixed amount",
            ),
        ),
        migrations.AlterField(
            model_name="pricingrule",
            name="target_package",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank to apply to all packages",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricing_rules",
                to="packages.package",
            ),
        ),
        migrations.AlterField(
            model_name="pricingrule",
            name="value",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                help_text="Percentage (e.g., 18 for 18%) or fixed amount",
                max_digits=10,
            ),
        ),
        migrations.CreateModel(
            name="PricingConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chargeable_age_threshold",
                    models.IntegerField(
                        default=5,
                        help_text="Minimum age for chargeable travelers (default: 5 years)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(18),
                        ],
                    ),
                ),
                (
                    "seasonal_pricing_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Seasonal pricing rules: {"summer": {"start": "06-01", "end": "08-31", "multiplier": 1.2}}',
                    ),
                ),
                (
                    "weekend_days",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Days considered as weekend (0=Monday, 6=Sunday). Default: [4, 5, 6] for Fri-Sun",
                    ),
                ),
                (
                    "default_weekend_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.3,
                        help_text="Default weekend price multiplier (e.g., 1.3 = 30% increase)",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(3.0),
                        ],
                    ),
                ),
                (
                    "min_advance_booking_days",
                    models.IntegerField(
                        default=1,
                        help_text="Minimum days in advance for booking (default: 1 day)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(365),
                        ],
                    ),
                ),
                (
                    "max_advance_booking_days",
                    models.IntegerField(
                        default=365,
                        help_text="Maximum days in advance for booking (default: 365 days)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(730),
                        ],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pricing_config_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pricing Configuration",
                "verbose_name_plural": "Pricing Configuration",
            },
        ),
    ]
