# Generated by Django 5.2 on 2026-02-22 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing_engine", "0003_add_pricing_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingconfiguration",
            name="enable_price_change_alerts",
            field=models.BooleanField(
                default=True,
                help_text="Enable admin alerts for significant price changes",
            ),
        ),
        migrations.AddField(
            model_name="pricingconfiguration",
            name="gst_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=18.0,
                help_text="GST rate in percentage (default: 18%)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="pricingconfiguration",
            name="platform_fee_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=2.0,
                help_text="Platform fee rate in percentage (default: 2%)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="pricingconfiguration",
            name="price_change_alert_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=5.0,
                help_text="Alert threshold for price changes in percentage (default: 5%)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="pricingconfiguration",
            name="price_lock_duration_minutes",
            field=models.IntegerField(
                default=15,
                help_text="Duration in minutes to lock price for booking (default: 15 minutes)",
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(60),
                ],
            ),
        ),
    ]
