# Generated by Django 5.2 on 2026-02-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Customer's full name", max_length=255),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Customer's email address", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Customer's phone number (optional)",
                        max_length=20,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("booking", "Booking Inquiry"),
                            ("package", "Package Customization"),
                            ("support", "Customer Support"),
                            ("feedback", "Feedback"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Inquiry subject/category",
                        max_length=50,
                    ),
                ),
                ("message", models.TextField(help_text="Customer's message")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("IN_PROGRESS", "In Progress"),
                            ("RESOLVED", "Resolved"),
                        ],
                        db_index=True,
                        default="NEW",
                        help_text="Current status of the inquiry",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes for admin use only"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="When the inquiry was resolved", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the inquiry was submitted",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestamp"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Submitter's IP address for spam prevention",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="Browser user agent for analytics"
                    ),
                ),
            ],
            options={
                "verbose_name": "Inquiry",
                "verbose_name_plural": "Inquiries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="inquiries_i_created_2b1632_idx"
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="inquiries_i_status_152cc6_idx",
                    ),
                    models.Index(fields=["email"], name="inquiries_i_email_415ef2_idx"),
                ],
            },
        ),
    ]
