# Generated by Django 5.2 on 2026-02-15 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("search", "0001_add_search_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PopularSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(db_index=True, max_length=200, unique=True)),
                ("search_count", models.IntegerField(default=0)),
                ("click_count", models.IntegerField(default=0)),
                ("avg_result_count", models.FloatField(default=0)),
                ("last_searched", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Popular Search",
                "verbose_name_plural": "Popular Searches",
                "ordering": ["-search_count"],
            },
        ),
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(db_index=True, max_length=200)),
                ("result_count", models.IntegerField(default=0)),
                ("search_time_ms", models.FloatField(default=0)),
                ("categories", models.CharField(blank=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Search Query",
                "verbose_name_plural": "Search Queries",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SearchClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result_type", models.CharField(max_length=50)),
                ("result_id", models.IntegerField()),
                ("result_title", models.CharField(max_length=255)),
                ("position", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "search_query",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="search.searchquery",
                    ),
                ),
            ],
            options={
                "verbose_name": "Search Click",
                "verbose_name_plural": "Search Clicks",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(
                fields=["query", "timestamp"], name="search_sear_query_1f4fd2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(
                fields=["result_count"], name="search_sear_result__794ea1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(
                fields=["timestamp"], name="search_sear_timesta_c1d6d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchclick",
            index=models.Index(
                fields=["result_type", "result_id"],
                name="search_sear_result__9c8bd0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="searchclick",
            index=models.Index(
                fields=["timestamp"], name="search_sear_timesta_6cc94d_idx"
            ),
        ),
    ]
