# Generated by Django 5.2 on 2026-02-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_alter_city_created_at_alter_city_name_and_more'),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='hoteltier',
            options={'ordering': ['price_multiplier']},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='transportoption',
            options={'ordering': ['base_price']},
        ),
        migrations.AlterField(
            model_name='experience',
            name='base_price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='experience',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='hoteltier',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hoteltier',
            name='price_multiplier',
            field=models.DecimalField(db_index=True, decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='package',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='transportoption',
            name='base_price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transportoption',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['name', 'base_price'], name='packages_ex_name_e28d00_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['base_price', 'created_at'], name='packages_ex_base_pr_0e84c4_idx'),
        ),
        migrations.AddIndex(
            model_name='hoteltier',
            index=models.Index(fields=['price_multiplier'], name='packages_ho_price_m_512ffd_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['city', 'is_active'], name='packages_pa_city_id_fc02bd_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['is_active', 'created_at'], name='packages_pa_is_acti_1976cb_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['name', 'is_active'], name='packages_pa_name_9a6305_idx'),
        ),
        migrations.AddIndex(
            model_name='transportoption',
            index=models.Index(fields=['base_price'], name='packages_tr_base_pr_ced009_idx'),
        ),
    ]
