# Generated by Django 5.2 on 2026-02-10 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0004_experience_enhancements"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="experience",
            new_name="packages_ex_categor_8f470e_idx",
            old_name="packages_ex_categor_idx",
        ),
        migrations.RenameIndex(
            model_name="experience",
            new_name="packages_ex_city_id_e02735_idx",
            old_name="packages_ex_city_is_idx",
        ),
        migrations.RenameIndex(
            model_name="experience",
            new_name="packages_ex_is_acti_30a37d_idx",
            old_name="packages_ex_is_acti_idx",
        ),
        migrations.AlterField(
            model_name="experience",
            name="base_price",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                help_text="Price in INR (₹100 - ₹100,000)",
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        100, message="Base price must be at least ₹100"
                    ),
                    django.core.validators.MaxValueValidator(
                        100000, message="Base price cannot exceed ₹100,000"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="experience",
            name="duration_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=2.5,
                help_text="Duration in hours (minimum 0.5 hours)",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(
                        0.5, message="Duration must be at least 0.5 hours"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="experience",
            name="max_participants",
            field=models.IntegerField(
                default=15,
                help_text="Maximum number of participants (minimum 1)",
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Must allow at least 1 participant"
                    )
                ],
            ),
        ),
    ]
