# Generated by Django 5.2 on 2026-02-12 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_library", "0002_alter_media_options"),
        (
            "packages",
            "0005_rename_packages_ex_categor_idx_packages_ex_categor_8f470e_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="featured_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Main image for the package displayed in listings and detail pages",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="packages",
                to="media_library.media",
            ),
        ),
    ]
