# Generated by Django 5.2 on 2026-02-21 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0007_phase1_hotel_tier_redesign"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="hoteltier",
            new_name="packages_ho_base_pr_06e56a_idx",
            old_name="packages_ho_base_pr_idx",
        ),
    ]
