# Generated by Django 5.2 on 2026-02-24 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0011_add_vehicle_optimization_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="transportoption",
            new_name="packages_tr_base_pr_7520ac_idx",
            old_name="packages_tra_base_pr_idx",
        ),
        migrations.RenameIndex(
            model_name="transportoption",
            new_name="packages_tr_is_acti_fd316c_idx",
            old_name="packages_tra_is_acti_idx",
        ),
        migrations.AlterField(
            model_name="experience",
            name="base_price",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                help_text="Price in INR (₹0 - ₹100,000). Set to 0 for free experiences.",
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        0,
                        message="Base price must be at least ₹0 (free experiences allowed)",
                    ),
                    django.core.validators.MaxValueValidator(
                        100000, message="Base price cannot exceed ₹100,000"
                    ),
                ],
            ),
        ),
    ]
