# Generated by Django 5.2 on 2026-02-28 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_library", "0004_media_updated_at"),
        ("packages", "0012_allow_free_experiences"),
    ]

    operations = [
        migrations.AddField(
            model_name="hoteltier",
            name="curation_promise",
            field=models.TextField(
                blank=True,
                default="",
                help_text='Why did we pick this tier? E.g., "Handpicked heritage stays for an authentic cultural immersion."',
            ),
        ),
        migrations.AddField(
            model_name="hoteltier",
            name="featured_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Visual representation of the experience this tier offers",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hotel_tiers",
                to="media_library.media",
            ),
        ),
    ]
