# Generated by Django 5.2 on 2026-02-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_alter_booking_options_alter_booking_created_at_and_more"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="razorpay_order_id",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(db_index=True, default="PENDING", max_length=20),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status", "created_at"], name="payments_pa_status_343680_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["amount", "status"], name="payments_pa_amount_2c65e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["booking", "status"], name="payments_pa_booking_57d6de_idx"
            ),
        ),
    ]
