# Generated by Django 5.2 on 2026-02-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_alter_article_options_alter_article_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to="articles/"),
        ),
    ]
