# Generated by Django 4.2.28 on 2026-02-04 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("packages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_PAYMENT", "Pending Payment"),
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="packages.package",
                    ),
                ),
                (
                    "selected_experiences",
                    models.ManyToManyField(to="packages.experience"),
                ),
                (
                    "selected_hotel_tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="packages.hoteltier",
                    ),
                ),
                (
                    "selected_transport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="packages.transportoption",
                    ),
                ),
            ],
        ),
    ]
