# Generated by Django 5.2 on 2026-02-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_alter_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Expiration time for DRAFT bookings (auto-set to 20 minutes after creation)",
                null=True,
            ),
        ),
    ]
