# Generated by Django 5.2 on 2026-02-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_booking_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="traveler_details",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of traveler information: [{name, age, gender}, ...]",
            ),
        ),
    ]
