# Generated by Django 5.2 on 2026-02-22 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0009_phase1_hotel_tier_redesign"),
        ("packages", "0008_phase1_hotel_tier_redesign"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "draft_data",
                    models.JSONField(
                        default=dict,
                        help_text='\n        Complete draft state:\n        {\n            "packageId": int,\n            "experiences": [int],\n            "days": int,\n            "dateRange": {"start": str, "end": str},\n            "travellers": [{"id": str, "name": str, "age": int, "gender": str, "isChild": bool}],\n            "hotelTier": int,\n            "rooms": [{"id": str, "type": str, "occupants": [str]}],\n            "vehicles": [{"id": str, "type": str, "passengers": [str]}],\n            "pricingEstimate": {"base": float, "experiences": float, "totalEstimate": float},\n            "status": str,\n            "versionToken": str\n        }\n        ',
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True, help_text="Draft expires 24 hours after creation"
                    ),
                ),
                (
                    "migrated_from_local",
                    models.BooleanField(
                        default=False,
                        help_text="True if this draft was migrated from localStorage",
                    ),
                ),
                (
                    "local_storage_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Original localStorage key for tracking",
                        max_length=255,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1,
                        help_text="Incremented on each update for optimistic locking",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        help_text="Package being booked",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="packages.package",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who owns this draft. Null for pre-login drafts.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Draft",
                "verbose_name_plural": "Booking Drafts",
                "db_table": "booking_drafts",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "expires_at"],
                        name="booking_dra_user_id_d1df05_idx",
                    ),
                    models.Index(
                        fields=["expires_at", "created_at"],
                        name="booking_dra_expires_7c4892_idx",
                    ),
                    models.Index(
                        fields=["package", "user"],
                        name="booking_dra_package_b9ffb3_idx",
                    ),
                ],
            },
        ),
    ]
