# Generated by Django 5.2 on 2026-02-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travelers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="traveler",
            name="passport_number",
        ),
        migrations.AddField(
            model_name="traveler",
            name="aadhaar_number",
            field=models.CharField(
                blank=True,
                help_text="Aadhaar number (optional)",
                max_length=12,
                null=True,
            ),
        ),
    ]
