# Generated by Django 5.2 on 2026-02-04 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media_library", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="media",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Media",
                "verbose_name_plural": "Media",
            },
        ),
    ]
