# Generated by Django 5.2 on 2026-02-12 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("media_library", "0002_alter_media_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
